In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [25]:
df.columns = df.columns.str.lower()

In [26]:
df.head()

,passengerid,name,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [27]:
df.drop(['passengerid', 'name', 'sibsp', 'parch', 'ticket', 'cabin', 'embarked'], axis='columns', inplace=True)
df.head()

   pclass     sex   age     fare  survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [28]:
inputs = df.drop('survived',axis='columns')

In [29]:
target = df['survived']

In [30]:
inputs.sex = inputs.sex.map({'male': 1, 'female': 2})

In [31]:
dummies = pd.get_dummies(inputs.sex)
dummies

         1      2
0     True  False
1    False   True
2    False   True
3    False   True
4     True  False
..     ...    ...
886   True  False
887  False   True
888  False   True
889   True  False
890   True  False

[891 rows x 2 columns]

In [32]:
inputs = pd.concat([inputs, dummies], axis='columns')

In [33]:
inputs.head(3)

   pclass  sex   age     fare      1      2
0       3    1  22.0   7.2500   True  False
1       1    2  38.0  71.2833  False   True
2       3    2  26.0   7.9250  False   True

In [34]:
inputs.rename(columns={1: 'male', 2: 'female'})

     pclass  sex   age     fare   male  female
0         3    1  22.0   7.2500   True   False
1         1    2  38.0  71.2833  False    True
2         3    2  26.0   7.9250  False    True
3         1    2  35.0  53.1000  False    True
4         3    1  35.0   8.0500   True   False
..      ...  ...   ...      ...    ...     ...
886       2    1  27.0  13.0000   True   False
887       1    2  19.0  30.0000  False    True
888       3    2   NaN  23.4500  False    True
889       1    1  26.0  30.0000   True   False
890       3    1  32.0   7.7500   True   False

[891 rows x 6 columns]

In [35]:
inputs.drop(['sex', 'male'], axis='columns', inplace=True, errors='ignore')

In [36]:
inputs.columns[inputs.isna().any()]

Index(['age'], dtype='object')

In [37]:
inputs.age = inputs.age.fillna(inputs.age.mean())

In [38]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [39]:
from sklearn.naive_bayes import GaussianNB

In [42]:
model = GaussianNB(priors=None, var_smoothing=1e-09)

In [44]:
model.fit(X_train,y_train)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.